name: 'Github Trending Repos Email'
author: 'Talljack'
description: 'To send github trending repos to your email'

inputs:
  token:
    description: 'Your GITHUB_TOKEN'
    required: false
    default: '${{ github.token }}'
  sendTime:
    description: 'The time the email was sent'
    required: false
    default: '19:00'
  languages:
    description: 'Trending language repos'
    required: false
    default: '[]'
  dateRange:
    description: 'Trending repos time'
    required: false
    default: 'daily'
outputs:
  githubTrendingRepos:
    description: 'All languages github trending repos'

runs:
  using: 'node20'
  main: 'lib/index.js'

branding:
  icon: 'code'
  color: 'green'
