# send_email.py
import yagmail
import base64
import sys
import json

def send_email(username, password, recipient, subject, body):
    print("Sending email...")
    yag = yagmail.SMTP(username, password)
    yag.send(to=recipient, subject=subject, contents=body, prettify_html=False)
    print('Email sent successfully')

# Shared styles as short CSS classes (inline for email compatibility)
S = {
    'td': 'border:1px solid #ddd;padding:8px;',
    'th': 'border:1px solid #ddd;padding:8px;background:#f5f5f5;',
    'link': 'color:#0366d6;text-decoration:none;',
    'sub': 'color:#666;font-size:12px;',
}

def format_github_repos(language, repos):
    if not repos:
        return ""
    lang = language.capitalize() if language and language != 'All' else 'All'
    rows = ''.join([f'<tr><td style="{S["td"]}"><a href="https://github.com{r["link"]}" style="{S["link"]}">{r["title"]}</a></td><td style="{S["td"]}">{(r.get("description","") or "")[:80]}</td><td style="{S["td"]}">⭐{r["stars"]}</td><td style="{S["td"]}">{r["todayStars"]}</td></tr>' for r in repos[:10]])
    return f'<h3>📦 {lang}</h3><table style="width:100%;border-collapse:collapse;margin-bottom:15px;"><tr><th style="{S["th"]}">Repo</th><th style="{S["th"]}">Desc</th><th style="{S["th"]}">Stars</th><th style="{S["th"]}">Today</th></tr>{rows}</table>'

def format_huggingface(models):
    if not models:
        return ""
    rows = ''.join([f'<tr><td style="{S["td"]}"><a href="{m["link"]}" style="color:#ff9d00;">{m["modelId"]}</a></td><td style="{S["td"]}">{m.get("downloads",0):,}</td><td style="{S["td"]}">{m.get("likes",0)}</td><td style="{S["td"]}">{m.get("pipeline_tag","")}</td></tr>' for m in models[:10]])
    return f'<h2 style="color:#ff9d00;">🤖 HuggingFace Models</h2><table style="width:100%;border-collapse:collapse;margin-bottom:15px;"><tr><th style="{S["th"]}">Model</th><th style="{S["th"]}">Downloads</th><th style="{S["th"]}">Likes</th><th style="{S["th"]}">Type</th></tr>{rows}</table>'

def format_hackernews(stories):
    if not stories:
        return ""
    items = ''.join([f'<div style="padding:8px;border-bottom:1px solid #eee;"><a href="{s["link"]}" style="color:#ff6600;">{s["title"]}</a><br/><span style="{S["sub"]}">▲{s["score"]} | {s["by"]} | {s.get("descendants",0)} comments</span></div>' for s in stories[:10]])
    return f'<h2 style="color:#ff6600;">📰 Hacker News</h2>{items}'

def format_devto(articles):
    if not articles:
        return ""
    items = ''.join([f'<div style="padding:8px;border-bottom:1px solid #eee;"><a href="{a["url"]}" style="color:#3b49df;">{a["title"]}</a><br/><span style="{S["sub"]}">{a["user"]["name"]} | ❤️{a.get("publicReactionsCount",0)}</span></div>' for a in articles[:10]])
    return f'<h2 style="color:#3b49df;">📝 Dev.to</h2>{items}'

def format_papers(papers):
    if not papers:
        return ""
    items = ''.join([f'<div style="padding:8px;border-bottom:1px solid #eee;"><a href="{p["url"]}" style="color:#673ab7;">{p["title"]}</a><br/><span style="{S["sub"]}">{", ".join(p.get("authors",[])[:2])} | ❤️{p.get("likes",0)}</span></div>' for p in papers[:10]])
    return f'<h2 style="color:#673ab7;">📄 AI Papers</h2>{items}'

def format_indie(revenues):
    if not revenues:
        return ""
    rows = ''.join([f'<tr><td style="{S["td"]}">{r.get("rank","-")}</td><td style="{S["td"]}">{r["name"]}</td><td style="{S["td"]}">${r.get("arr",0):,.0f}</td><td style="{S["td"]}">${r.get("mrr",0):,.0f}/mo</td></tr>' for r in revenues[:10]])
    return f'<h2 style="color:#10b981;">💰 Indie Revenue</h2><table style="width:100%;border-collapse:collapse;"><tr><th style="{S["th"]}">#</th><th style="{S["th"]}">Product</th><th style="{S["th"]}">ARR</th><th style="{S["th"]}">MRR</th></tr>{rows}</table>'

def format_email(data):
    html = '<html><body style="font-family:Arial,sans-serif;max-width:800px;margin:0 auto;padding:20px;">'
    html += '<h1 style="text-align:center;">🔥 Tech Trending Daily</h1>'
    
    if 'githubTrending' in data:
        gh = data['githubTrending']
        all_repos = gh.get('', gh.get('all', gh.get('All', [])))
        if all_repos:
            html += format_github_repos('All', all_repos)
        for lang in sorted([k for k in gh.keys() if k and k.lower() not in ['all', '']]):
            html += format_github_repos(lang, gh[lang])
    
    html += format_huggingface(data.get('huggingFaceModels'))
    html += format_hackernews(data.get('hackerNewsStories'))
    html += format_devto(data.get('devToArticles'))
    html += format_papers(data.get('aiPapers'))
    html += format_indie(data.get('indieRevenue'))
    
    html += '<p style="text-align:center;color:#999;font-size:12px;margin-top:30px;">Generated by Tech Trending Daily 🚀</p>'
    html += '</body></html>'
    return html

if __name__ == '__main__':
    username = sys.argv[1]
    password = sys.argv[2]
    recipient = sys.argv[3]
    subject = sys.argv[4]
    data_base64 = sys.argv[5]
    
    decoded_bytes = base64.urlsafe_b64decode(data_base64)
    data = json.loads(decoded_bytes.decode('utf-8'))
    content = format_email(data)
    
    # Print size for debugging
    print(f"Email HTML size: {len(content)} bytes ({len(content)/1024:.1f} KB)")
    
    send_email(username, password, recipient, subject, content)
